spring:
  application:
    name:
      spoc-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.148.193.100:3306/spoc_lite?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  # ?????????? (?????????? create_time ???? Java ? createTime)
  configuration:
    map-underscore-to-camel-case: true
    # ??????????? SQL?????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # ?? MyBatis ???? XML ??
  mapper-locations: classpath:mapper/*.xml
  # ?? MyBatis ?????? (?????? XML ?? resultType ????????)
  type-aliases-package: com.spoc.entity